os: linux
dist: trusty
language: java
jdk:
  - openjdk8
install: "/bin/true"
script:
  - mvn clean install -q -B
env:
  global:
    - secure: iKY6rCO8DvZ8NtQpZmjyZuKwmvGBlu8T2VzdzIn2UMGlNc+nQjWPA6UkODLj5wTr/h0TMZjHGlhbkW4sGDm3WDrZM+HvPjUC+ljVdtGeydGqRU6/5PdRPm1qD/jh0W8dss0vnWC7G7ouathc53hS/PkoC8Gsrup23JRJyurfM2+YsoJrMf9So3GbP7n5XAUyCUoh9YKGvFUsB492Casl/rkfiT858KhdblAarX4TfIoJAK4x/5+6a+t/P9kIK314JncQi1IAGS37hVG2UCKTrfbiTXah7f231bp494IASR4goNBazcHiVq7Eq2oq5YzaD9RH1aHW1MhvjwNZlSGhyUlkBsuf1wT9KtjjUxKFN50wxOEH5PtLhDBKpiifVl0Z2GBtCqDayQcg5codYEvbQncQN8QNsHO02WQNHpfPrxGxnE0zbRq/VMkpisjAPbaYXjK4ESGblTyCBE/mOeGyE/KVREeg0AoWvZ3PCazipVihzt6cdm6gDb97Bk5gG+nOLowMjrkvdjroZr0UPrI1s73YjSzn6/uDBE1ZORQV3+Oo6IeN3L8tmn1VcdGdfdY44hCy9IVkyZj1K7muJT2/oq6o5QJkl1Hsdq4M4UgsCo0unfx3FmCxIcqnlDGgsz4Sk2WfGzv5xQS+gdmAzI1Pk7UzVaMdJrpk2jEnsE6DPYY=
    - secure: 5ZzwvdzGAslxdsOib9sw8fXbt6F2ZENeqaXMO6tKnVw1BvyjKwgW2ZZqaFa2bnX9VdAqr3/9EzVoRhfdPGA9lL2xoXXrAJs9gnyh44XQospptmyj/Zz/gPYDBNR8zFbRCrZxEFEgQfXks0Bvoap8/WCShdjHibssWcPxEz6qOPHdqmmyBmUcKDVRU+rLsIuVxEeqBqbd0aQgVwQFpQkdmwrptxTP9TqHRc+Z9pfqZhzyc9C+5qa6HNN3zTz0gKXkp/ac7Y7Wn2ejQAfBQ+gGS7NpEg2tGX/WZgPBLgOXrISJT4hjLc8x16aB3ib5lvkj+0h27fyomxLaAx1b6eor7uvZBCe2JA7JEbuEeajwdCi+V4RsacsSS4ORcnSREGKJT8tTHR6/d7Zahhp285cKBCdH60AbaImNXhxLlBC6dQN0PAXvIxaZhNz35nvIYHT9kq9WJam1S/r9b9dNRqrNl+cK2ikhD2Im0aW9FalZ7VPX9daJoTeAXUkqC4yOCV30wTeujdRWhYWHlC0JDGjaHHstE9L13AhuqRRoZFpZglkv2+nbQZH2EgzbjqutXm0cIev84syNW2CrJGQFT47OrNTD1tU0w0CYU7HZptct21Vsp1d/WgDLiB1bLPmDYhVsGGbmV2/zRhoA0OT8kRU/3pG5XU0/gpcQ3juEOLyNVxg=
    - secure: lZ47ZbD6V3CndJmOrtP0tuBUMTTucCTMufAui9/WKq86xlqNeFet2l/R6d3x0DvNpeKqnkgpw0OueXOt6cXT2WJELYW6DY91kpi1xgM7WpZ72ULBVzowzTBwz0ICq2EsqEvRdy0w3ZnUsjenh+Eqh2eoX6yhP8Cp+SvUd3nE9hjiB3Pu6d2GJ5jag2lKeG2bodPgabJ3xvx/IABh+xKa8w2gNdvQYGEGmfhTRAzjZJsqDq8WToc8lFQ3jryoyBjOVaKE/hY2a+t6KgOAiAkP5TtedTEA5giT4sLpKgB1Fy8nDhM2cFcNzIZnTGfqS74tCxJuaSzjEcn7wsEXMZ66djgN7ESdsqwCp45tsOmsfirKZ8yZSzp06pOG7YoAV7lwCG7ul+/xtC72RrJHdDqo2gVEiS1tOEa93xQ87RqBSXGCuajZkWGjPQ0Tw9OkxvLzf9ETQH/Wd06Tgy5t1s0ZbN8Q6ualJVgyL1lXWm62r7Lr7n0BMUVI5YFFb5Wu8JglpgudY5pAtOz8P7CsoXahgfSVeSps5Aab+krgLoHs6eIqnrLLLt+uXN0BjJSwU5ZqBHqsooiRlusKoPLdbmulEgYjvGk8SrYhRxc5w4+ESs18V+ekJB4EOB780SoI2VPVCsILRZvulZeDmoHdDQ3fCeCLVm/T2cFfSJIj5XsubNM=
    - secure: fSDteeXRWerHeix4F0vZBSEIc9xJd5DPHr7yP4JHj6VuwXE49DLHZw4PixohUwJeVXDakcvdsgjEdpcSmEcIufcqBgKUAQxekuS/rz192LsCGvPxwB4RgQHYbSFAfLSrFp/EGQv4uFlko6/qHv8OFRp2MnpJO0kAtj3rP8r5gNpxeZxusmWp0U3CEoDYSXZ3H1geNjYK5W/Cp2Po1xC0TCOQjz5eV2Ds6LNFOKF9iBDoxviyPyFotQc9Q7Di+/f/1jKjtk4qKWJpD4SPYrq99+hMyUUUmhvLClPWmb9tJ/RLgvyAhaiEE2SOWLvZjye6zqfbW1VDMDnOYoIQVxYOz1GB8goFLZvFygdYI/bVekE56yXytIpGqPdZVdDr67/v+4qU+bVJ7GM6dtCBVLeD4Y/kmIaRoKf3pajkhSXeP6E3NpeXS9KH3h16IjDPtQ5EPh+X1KrloekE5yEZ/ey2vqjrqCmRAuSvbA4VSqsxXvPffilX55QGP0PZtk387z+/HBQUw+w1aGjmp/TUWlQhl25Os/8FVIB8EqksxefwOcYzYeNLgB424llocyGtnqnyqDI0DMrN5OFWkBKdetTz0+bwfVrJ+S7cYykMuq7PeCNHTVjq3rTHK//S7gkJeV8ABb0mHViRYCEatoKpPETejD/IEk4LNW1RKw5SrheZal0=
before_deploy:
  - openssl aes-256-cbc -K $encrypted_4c33f5d5b8d1_key -iv $encrypted_4c33f5d5b8d
    -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
deploy:
  - skip_cleanup: true
    provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash) -t bb50f714-cd28-46ba-a397-cfcb188aa526